AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance for Assignment 3'

Parameters:
  InstanceType:
    Description: 'EC2 instance type'
    Type: String
    Default: 't2.micro'

  KeyName:
    Description: 'Name of an existing EC2 KeyPair to enable SSH access'
    Type: 'AWS::EC2::KeyPair::prog8870-key'
    ConstraintDescription: 'Must be the name of an existing EC2 KeyPair.'

  AMIId:
    Description: 'AMI ID for the EC2 instance'
    Type: 'AWS::EC2::Image::Id'
    Default: 'ami-0150ccaf51ab55a51' # Amazon Linux 2023 in us-east-1

Resources:
  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable SSH access'
      VpcId:
        Fn::ImportValue: 'Assignment3-VPC-ID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: 'Assignment3-EC2-SG'

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIId
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref EC2SecurityGroup
          SubnetId:
            Fn::ImportValue: 'Assignment3-PublicSubnet-ID'
      Tags:
        - Key: Name
          Value: 'Assignment3-EC2'

Outputs:
  InstanceId:
    Description: 'Instance ID of the newly created EC2 instance'
    Value: !Ref EC2Instance

  PublicIP:
    Description: 'Public IP address of the newly created EC2 instance'
    Value: !GetAtt EC2Instance.PublicIp

  SecurityGroupId:
    Description: 'Security Group ID for the EC2 instance'
    Value: !Ref EC2SecurityGroup
    Export:
      Name: 'Assignment3-EC2-SG-ID'