AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance Deployment for Assignment 3 - Student ID: 9015480'

Parameters:
  AmiId:
    Description: 'Amazon Machine Image ID for Student 9015480'
    Type: 'AWS::EC2::Image::Id'
    Default: 'ami-0c7217cdde317cfec' # Amazon Linux 2 in us-east-1

  InstanceType:
    Description: 'EC2 instance type for Student 9015480'
    Type: String
    Default: 't2.micro'
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  KeyPairName:
    Description: 'Existing EC2 Key Pair name for SSH access (Student 9015480)'
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: 'prog8870-key'

Resources:
  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group for EC2 Instance - Student 9015480'
      VpcId:
        Fn::ImportValue: 'Assignment3-VPC-ID-9015480'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: 'Assignment3-EC2-SG-9015480'
        - Key: StudentID
          Value: '9015480'

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref EC2SecurityGroup
          SubnetId:
            Fn::ImportValue: 'Assignment3-PublicSubnet-ID-9015480'
      Tags:
        - Key: Name
          Value: 'Assignment3-EC2-9015480'
        - Key: StudentID
          Value: '9015480'
      UserData:
        Fn::Base64: |
          #!/bin/bash
          echo "EC2 Instance deployed by Student 9015480" > /home/ec2-user/student_id.txt

Outputs:
  InstanceId:
    Description: 'Instance ID of the EC2 instance for Student 9015480'
    Value: !Ref EC2Instance

  PublicIP:
    Description: 'Public IP address of the EC2 instance for Student 9015480'
    Value: !GetAtt EC2Instance.PublicIp

  PublicDNS:
    Description: 'Public DNS name of the EC2 instance for Student 9015480'
    Value: !GetAtt EC2Instance.PublicDnsName

  SecurityGroupId:
    Description: 'Security Group ID for Student 9015480'
    Value: !Ref EC2SecurityGroup