AWSTemplateFormatVersion: "2010-09-09"
Description: "Assignment 3 - EC2 Instance"

Parameters:
  AMIId:
    Type: String
  InstanceType:
    Type: String
    Default: t2.micro
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  Assignment3SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId: !ImportValue Assignment3-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  Assignment3EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !ImportValue Assignment3-Subnet1-ID
          GroupSet:
            - !Ref Assignment3SecurityGroup
      Tags:
        - Key: Name
          Value: assignment3

Outputs:
  EC2PublicIP:
    Value: !GetAtt Assignment3EC2Instance.PublicIp
    Description: Public IP of the EC2 instance
