AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL instance with public accessibility and security group

Parameters:
  VPCId:
    Type: String
    Description: VPC ID where RDS will be launched
  SubnetId:
    Type: String
    Description: Subnet ID for RDS instance
  DBUsername:
    Type: String
    Default: admin
    NoEcho: true
    Description: Master username for RDS
  DBPassword:
    Type: String
    NoEcho: true
    Description: Master user password for RDS
  DBInstanceClass:
    Type: String
    Default: db.t2.micro
    Description: RDS instance class

Resources:
  RDSSecurityGroupPROG8870:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: RDSSecurityGroup-PROG8870

  RDSSubnetGroupPROG8870:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds:
        - !Ref SubnetId
      Tags:
        - Key: Name
          Value: RDSSubnetGroup-PROG8870

  RDSInstancePROG8870:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: assignment3
      AllocatedStorage: 20
      DBInstanceClass: !Ref DBInstanceClass
      Engine: mysql
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref RDSSecurityGroupPROG8870
      DBSubnetGroupName: !Ref RDSSubnetGroupPROG8870
      PubliclyAccessible: true
      MultiAZ: false
      StorageType: gp2
      BackupRetentionPeriod: 7
      Tags:
        - Key: Name
          Value: RDSInstance-PROG8870

Outputs:
  RDSInstanceEndpoint:
    Description: Endpoint of the RDS instance
    Value: !GetAtt RDSInstancePROG8870.Endpoint.Address

  RDSInstanceId:
    Description: RDS Instance ID
    Value: !Ref RDSInstancePROG8870
