AWSTemplateFormatVersion: "2010-09-09"
Description: "Assignment 3 - RDS MySQL Instance"

Parameters:
  DBUsername:
    Type: String
    NoEcho: true
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  Assignment3RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL traffic
      VpcId: !ImportValue Assignment3-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  Assignment3RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "RDS subnet group for assignment3"
      SubnetIds:
        - !ImportValue Assignment3-Subnet1-ID
        - !ImportValue Assignment3-Subnet2-ID
      DBSubnetGroupName: assignment3-subnet-group

  Assignment3RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: assignment3-db
      DBName: assignment3
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref Assignment3RDSSecurityGroup
      DBSubnetGroupName: !Ref Assignment3RDSSubnetGroup
      PubliclyAccessible: true
      BackupRetentionPeriod: 0
      Tags:
        - Key: Name
          Value: assignment3

Outputs:
  RDSEndpoint:
    Description: RDS endpoint
    Value: !GetAtt Assignment3RDSInstance.Endpoint.Address
